### ISSUE TITLE
Lizenz?

### ISSUE THREAD

**Issue by RNitzsche** [tschuegge/SqlKurs#1]
Grüezi,
ich bin auf Deine SQLITE-Datenbank gestoßen, habe aber noch keine Gelegenheit gehabt, mir den Kurs anzusehen.
Die Datenbank gefällt mir aber schon mal sehr. 

Unter welcher Lizenz steht sie? Ich denke gerade darüber nach, mein Instahub-Skript (https://github.com/RNitzsche/instahub-doc-de) neben der Terra-Datenbank noch mit einer weiteren Alternative zu versehen und die Datenbank dazu evtl. nochmal etwas "germanisieren", Umsatzsteuersätze z.B.

Herzliche Grüße

RNitzsche

**Comment by tschuegge** [comment]
Hallo,
du kannst die Datenbank verwenden. Über eine Namensnennung würde ich mich freuen.
Durch einen Fork, kannst du auch die Daten "germanisieren" :-)
Liebe Grüsse aus der Schweiz
Jürg
